---
title: "R Basics Notes"
output: html_document
date: "2024-07-10"
---

# Some basic functions
log()

sqrt()

exp()

data() # see all datasets in whe workspace

install.packages()

library()

require()

length()

# Getting help
help("log")

help(log)

?log

args(log)

help("+") # help on + operator

# Data types
class(1234)
class(ls)
class(murders)  # data.frame: a dataset in library(dslabs)

# Factors
class(murders$region)
levels(murders$region)

# Vectors
codes <- c(380, 124, 818)
countries <- c("Italy", "Canada", "Egypt")
class(codes)
class(countries)
names(codes)

codes2 <- c(italy = 380, canada = 124, egypt = 818)
class(codes2)
names(codes2)
codes3 <- c("italy" = 380, "canada" = 124, "egypt" = 818)
class(codes3)
names(codes3)


seq(1, 10)
seq(1, 100, 10)
1:10
codes[2]
codes2[2]
codes2[1:3]
codes2["canada"]
codes2[c("canada", "italy")]

# Vector coercion
x <- c(1, "canada", 3)
class(x)
x # data is coerced to character
x <- 1:5
y <- as.character(x)
y
as.numeric(y)

# Missing data
x <- c("1", "b", "3")
as.numeric(x)  # NAs introduced by coercion



# Sorting
sort(murders$total) # vector sorted, but no info on state names

x <- c(31, 4, 15, 92, 65)
sort(x)
order(x) # indices of the sorted vector
index <- order(x)
x[index]
index
class(index)

index <- order(murders$total)
murders$abb[index]

max(murders$total)
which.max(murders$total)
murders$abb[which.max(murders$total)]
murders$abb[which.min(murders$total)]

rank(x) # rank in the sorted vector

# vector arithmetic
murders$state[which.max(murders$population)]
heights <- c(69, 62, 66, 70, 70, 73, 67, 73, 67, 70) # inches
heights * 2.54 # convert to centimeters
heights - 69

murder_rate <- murders$total/murders$population * 100000
murders$abb[order(murder_rate)]
murders$abb[order(murder_rate, decreasing = TRUE)]
murders$state[order(murder_rate, decreasing = TRUE)]

# indexing
index <- murder_rate < 0.71
murders$state[index]
sum(index) # how many states have murder_rate less than 0.71

west <- murders$region == "West"
safe <- murder_rate <= 1
sum(west & safe)
murders$state[west & safe]

# indexing functions: which, match, %in%
index <- which(murders$state == "Massachusetts") # index is much smaller now, not 51 bools
murders$state[index]

index <- match(c("New York", "Florida", "Texas"), murders$state)
index
murders$state[index]
murder_rate[index]

x <- c("a", "b", "c", "d", "e")
y <- c("a", "d", "f")
y %in% x

c("Boston", "Dakota", "Washington") %in% murders$state

population_in_millions <- murders$population / 10^6
total_gun_murders <- murders$total
# scatterplot
plot(population_in_millions, total_gun_murders)
# histograms
hist(murder_rate)
murders$state[which.max(murder_rate)]
# boxplot
boxplot(murder_rate ~ region, data = murders)

